#!/usr/bin/env python3
"""Run a detector with its FROZEN thresholds (config/thresholds.json) on a split and record metrics.

Writes results/data_integrity_eval.json and regenerates results/data_integrity_eval.md.
"""
from __future__ import annotations

import argparse
import platform
from datetime import datetime, timezone

from _common import CONFIG, DATA, RESULTS, ground_truth, read_json, sha256_file, write_json

from app.core import thresholds as th
from app.engines.data_integrity import evaluation, patch_trigger
from app.engines.data_integrity.dataset import load_yolo


def run_patch(split: str) -> dict:
    ev, _, _ = patch_trigger.detect(load_yolo(DATA / split / "dataset"), th.for_detector(patch_trigger.DETECTOR))
    return evaluation.score_patch(ground_truth(split), ev)


RUNNERS = {patch_trigger.DETECTOR: run_patch}


def evaluate(detector: str, split: str) -> dict:
    cfg = th.load()["detectors"][detector]
    if cfg["tuned_on"]["split"] != "tuning":
        raise SystemExit("thresholds must come from the tuning split")
    m = RUNNERS[detector](split)
    m["thresholds"] = cfg["thresholds"]
    m["detector_version"] = cfg["detector_version"]
    m["ground_truth_sha256"] = sha256_file(DATA / split / "ground_truth.json")
    return m


def render_md(res: dict) -> str:
    lines = ["# Data integrity engine: evaluation results", "",
             "Generated by `scripts/evaluate.py`; do not edit by hand. Thresholds are frozen in `config/thresholds.json` "
             "and were chosen on TUNING only. TEST is the held-out split. TUNING numbers are shown for reference and are optimistic "
             "because the thresholds were fitted on them.", "",
             "| detector | split | unit | planted | caught (TP) | false flags (FP) | clean images scanned | non-target scanned | precision | recall |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for det, splits in res["detectors"].items():
        for split in ("test", "tuning"):
            if split in splits:
                m = splits[split]
                lines.append(f"| {det} | {split.upper()} | {m['unit']} | {m['planted']} | {m['caught']} | {m['false_flags']} | "
                             f"{m['clean_images_scanned']} | {m['non_target_images_scanned']} | {m['precision']} | {m['recall']} |")
    lines += ["", "Definitions: *clean* = image with no plant of any kind. *non-target* = every scanned unit that is not a planted "
              "instance for that detector (includes images carrying other plant types). Precision = TP/(TP+FP), recall = TP/planted.", ""]
    for det, splits in res["detectors"].items():
        for split, m in splits.items():
            extra = {k: m[k] for k in m if k in ("false_flags_by_plant_type", "localisation_iou_mean", "missed_images", "false_flag_images")}
            lines.append(f"- `{det}` / {split}: {extra}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--detector", choices=sorted(RUNNERS), required=True)
    ap.add_argument("--split", choices=["tuning", "test"], action="append", required=True)
    a = ap.parse_args()
    res = read_json(RESULTS, {"detectors": {}})
    for split in a.split:
        m = evaluate(a.detector, split)
        res["detectors"].setdefault(a.detector, {})[split] = m
        print(a.detector, split, {k: m[k] for k in ("planted", "caught", "false_flags", "clean_images_scanned", "precision", "recall")})
    res["thresholds_sha256"] = sha256_file(CONFIG)
    res["environment"] = {"python": platform.python_version()}
    res["generated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    write_json(RESULTS, res)
    RESULTS.with_suffix(".md").write_text(render_md(res))


if __name__ == "__main__":
    main()
