#!/usr/bin/env python3
"""Run a detector with its FROZEN thresholds (config/thresholds.json) on a split and record metrics.

Writes results/data_integrity_eval.json and regenerates results/data_integrity_eval.md.
"""
from __future__ import annotations

import argparse
import platform
from datetime import datetime, timezone

from _common import CONFIG, DATA, RESULTS, ground_truth, read_json, sha256_file, write_json

from app.core import thresholds as th
from app.engines.data_integrity import evaluation, label_flip, near_duplicate, patch_trigger
from app.engines.data_integrity.dataset import load_yolo


def run_patch(split: str) -> dict:
    ev, _, _ = patch_trigger.detect(load_yolo(DATA / split / "dataset"), th.for_detector(patch_trigger.DETECTOR))
    return evaluation.score_patch(ground_truth(split), ev)


def run_flip(split: str) -> dict:
    cfg = th.load()["detectors"][label_flip.DETECTOR]
    ev, _, batch = label_flip.detect(load_yolo(DATA / split / "dataset"), cfg["thresholds"], label_flip.FlipParams(**cfg["params"]))
    m = evaluation.score_flip(ground_truth(split), ev, batch["boxes_assessed"], batch["boxes_below_min_side"])
    m["unit"] = "box+image"
    return m


def run_dup(split: str) -> dict:
    t = th.for_detector(near_duplicate.DETECTOR)
    ds = load_yolo(DATA / split / "dataset")
    gt = ground_truth(split)
    ev, _, batch = near_duplicate.detect(ds, t)
    m = evaluation.score_dup(gt, ev)
    m["mode"] = ev[0].measurements["mode"] if ev else ("phash+embedding" if batch["encoder"] else "phash_only")
    fb_ev, _, _ = near_duplicate.detect(ds, t, use_embeddings=False)
    fb = evaluation.score_dup(gt, fb_ev)
    m["phash_only_fallback"] = {lvl: {k: fb[lvl][k] for k in ("planted", "caught", "false_flags", "precision", "recall")}
                                for lvl in ("pair_level", "image_level")}
    m["unit"] = "pair+image"
    return m


RUNNERS = {patch_trigger.DETECTOR: run_patch, label_flip.DETECTOR: run_flip, near_duplicate.DETECTOR: run_dup}


def evaluate(detector: str, split: str) -> dict:
    cfg = th.load()["detectors"][detector]
    if cfg["tuned_on"]["split"] != "tuning":
        raise SystemExit("thresholds must come from the tuning split")
    m = RUNNERS[detector](split)
    m["thresholds"] = cfg["thresholds"]
    m["detector_version"] = cfg["detector_version"]
    m["ground_truth_sha256"] = sha256_file(DATA / split / "ground_truth.json")
    return m


def render_md(res: dict) -> str:
    lines = ["# Data integrity engine: evaluation results", "",
             "Generated by `scripts/evaluate.py`; do not edit by hand. Thresholds are frozen in `config/thresholds.json` "
             "and were chosen on TUNING only. TEST is the held-out split. TUNING numbers are shown for reference and are optimistic "
             "because the thresholds were fitted on them.", "",
             "| detector | split | unit | planted | caught (TP) | false flags (FP) | clean images scanned | non-target scanned | precision | recall |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for det, splits in res["detectors"].items():
        for split in ("test", "tuning"):
            if split in splits and "box_level" in splits[split]:
                b, i = splits[split]["box_level"], splits[split]["image_level"]
                lines.append(f"| {det} | {split.upper()} | box | {b['planted']} | {b['caught']} | {b['false_flags']} | "
                             f"{i['clean_images_scanned']} | {b['non_target_boxes_assessed']} boxes | {b['precision']} | {b['recall']} |")
                lines.append(f"| {det} | {split.upper()} | image | {i['planted']} | {i['caught']} | {i['false_flags']} | "
                             f"{i['clean_images_scanned']} | {i['non_target_images_scanned']} | {i['precision']} | {i['recall']} |")
            elif split in splits and "pair_level" in splits[split]:
                b, i = splits[split]["pair_level"], splits[split]["image_level"]
                lines.append(f"| {det} | {split.upper()} | pair | {b['planted']} | {b['caught']} | {b['false_flags']} | "
                             f"{i['clean_images_scanned']} | {b['pairs_compared'] - b['planted']} pairs | {b['precision']} | {b['recall']} |")
                lines.append(f"| {det} | {split.upper()} | image | {i['planted']} | {i['caught']} | {i['false_flags']} | "
                             f"{i['clean_images_scanned']} | {i['non_target_images_scanned']} | {i['precision']} | {i['recall']} |")
            elif split in splits:
                m = splits[split]
                lines.append(f"| {det} | {split.upper()} | {m['unit']} | {m['planted']} | {m['caught']} | {m['false_flags']} | "
                             f"{m['clean_images_scanned']} | {m['non_target_images_scanned']} | {m['precision']} | {m['recall']} |")
    lines += ["", "Definitions: *clean* = image with no plant of any kind. *non-target* = every scanned unit that is not a planted "
              "instance for that detector (includes images carrying other plant types). Precision = TP/(TP+FP), recall = TP/planted.", ""]
    for det, splits in res["detectors"].items():
        for split, m in splits.items():
            if "box_level" in m:
                b = m["box_level"]
                extra = {"boxes_assessed": b["boxes_assessed"], "boxes_below_min_side": b["boxes_below_min_side"],
                         "clean_image_boxes_flagged": b["clean_image_boxes_flagged"],
                         "image_false_flags_by_plant_type": m["image_level"]["false_flags_by_plant_type"]}
            elif "pair_level" in m:
                b = m["pair_level"]
                extra = {"mode": m["mode"], "false_pairs_by_category": b["false_pairs_by_category"],
                         "unplanted_same_sequence_pairs_present": b["unplanted_same_sequence_pairs_present"],
                         "unplanted_same_sequence_pairs_flagged": b["unplanted_same_sequence_pairs_flagged"],
                         "missed_pairs": b["missed_pairs"], "phash_only_fallback": m["phash_only_fallback"]}
            else:
                extra = {k: m[k] for k in m if k in ("false_flags_by_plant_type", "localisation_iou_mean", "missed_images", "false_flag_images")}
            lines.append(f"- `{det}` / {split}: {extra}")
            if "manual_review" in m:
                lines.append(f"  - manual review of false flags: {m['manual_review']['summary']}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--detector", choices=sorted(RUNNERS), required=True)
    ap.add_argument("--split", choices=["tuning", "test"], action="append", required=True)
    a = ap.parse_args()
    res = read_json(RESULTS, {"detectors": {}})
    for split in a.split:
        m = evaluate(a.detector, split)
        old = res["detectors"].get(a.detector, {}).get(split, {})
        if "manual_review" in old:
            m["manual_review"] = old["manual_review"]
        res["detectors"].setdefault(a.detector, {})[split] = m
        for lvl, mm in ([(k.split("_")[0], m[k]) for k in ("box_level", "pair_level", "image_level") if k in m] or [("image", m)]):
            print(a.detector, split, lvl, {k: mm.get(k) for k in ("planted", "caught", "false_flags", "clean_images_scanned", "boxes_assessed", "precision", "recall")})
    res["thresholds_sha256"] = sha256_file(CONFIG)
    res["environment"] = {"python": platform.python_version()}
    res["generated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    write_json(RESULTS, res)
    RESULTS.with_suffix(".md").write_text(render_md(res))


if __name__ == "__main__":
    main()
